// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRgdqwdq4Jny3VlDG90mk1NJB4cxQgl-0',
    appId: '1:168555285732:web:9a7e6227b38bbc5b49f0f1',
    messagingSenderId: '168555285732',
    projectId: 'vision-mart-app-a727d',
    authDomain: 'vision-mart-app-a727d.firebaseapp.com',
    storageBucket: 'vision-mart-app-a727d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW2vN5Q3uKww33K-4FbxQA-uG2HuGi9Bo',
    appId: '1:168555285732:android:a916f46c634aa72a49f0f1',
    messagingSenderId: '168555285732',
    projectId: 'vision-mart-app-a727d',
    storageBucket: 'vision-mart-app-a727d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWBHTtmH7bBvomk9yV2kBqvPqX8AxLq6M',
    appId: '1:168555285732:ios:4008b72b8b5a408249f0f1',
    messagingSenderId: '168555285732',
    projectId: 'vision-mart-app-a727d',
    storageBucket: 'vision-mart-app-a727d.firebasestorage.app',
    iosBundleId: 'com.example.visionMartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWBHTtmH7bBvomk9yV2kBqvPqX8AxLq6M',
    appId: '1:168555285732:ios:4008b72b8b5a408249f0f1',
    messagingSenderId: '168555285732',
    projectId: 'vision-mart-app-a727d',
    storageBucket: 'vision-mart-app-a727d.firebasestorage.app',
    iosBundleId: 'com.example.visionMartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRgdqwdq4Jny3VlDG90mk1NJB4cxQgl-0',
    appId: '1:168555285732:web:d79cef7d52deecc449f0f1',
    messagingSenderId: '168555285732',
    projectId: 'vision-mart-app-a727d',
    authDomain: 'vision-mart-app-a727d.firebaseapp.com',
    storageBucket: 'vision-mart-app-a727d.firebasestorage.app',
  );
}
