import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../data/expense_repository.dart';
import '../domain/expense_model.dart';

class AddBatchExpenseScreen extends ConsumerStatefulWidget {
  const AddBatchExpenseScreen({super.key});

  @override
  ConsumerState<AddBatchExpenseScreen> createState() => _AddBatchExpenseScreenState();
}

class _BatchItem {
  final TextEditingController amountCtrl = TextEditingController();
  final TextEditingController noteCtrl = TextEditingController();
  String category = 'Other';
  DateTime date = DateTime.now();
  final FocusNode amountFocus = FocusNode();

  void dispose() {
    amountCtrl.dispose();
    noteCtrl.dispose();
    amountFocus.dispose();
  }
}

class _AddBatchExpenseScreenState extends ConsumerState<AddBatchExpenseScreen> {
  final List<_BatchItem> _items = [];
  bool _isLoading = false;

  final List<String> _categories = [
    'Shop Rent', 'Electric Bill', 'Transport Cost',
    'Food Cost', 'Salary', 'Maintenance', 'Other'
  ];

  @override
  void initState() {
    super.initState();
    _addItem(); // Start with one item
  }

  void _addItem() {
    setState(() {
      _items.add(_BatchItem());
    });
  }

  void _removeItem(int index) {
    if (_items.length <= 1) return;
    final item = _items[index];
    setState(() {
      _items.removeAt(index);
    });
    item.dispose();
  }

  @override
  void dispose() {
    for (var item in _items) {
      item.dispose();
    }
    super.dispose();
  }

  Future<void> _saveAll() async {
    // Validate
    for (var item in _items) {
      if (item.amountCtrl.text.isEmpty) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text("Please enter amount for all items"), backgroundColor: Colors.red),
        );
        return;
      }
    }

    setState(() => _isLoading = true);

    try {
      final List<Expense> expensesToSave = _items.map((item) {
        return Expense(
          id: '', // Generated by Firestore
          category: item.category,
          amount: double.tryParse(item.amountCtrl.text) ?? 0,
          note: item.noteCtrl.text.trim(),
          date: item.date,
          recordedBy: '', // Handled by repo
        );
      }).toList();

      await ref.read(expenseRepositoryProvider).addBatchExpenses(expensesToSave);

      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Successfully added ${_items.length} expenses")),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Error: $e"), backgroundColor: Colors.red));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      appBar: AppBar(title: const Text("Add Batch Expenses")),
      body: Column(
        children: [
          Expanded(
            child: ListView.separated(
              padding: const EdgeInsets.all(16),
              itemCount: _items.length,
              separatorBuilder: (_, __) => const SizedBox(height: 16),
              itemBuilder: (context, index) {
                final item = _items[index];
                return Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: isDark ? const Color(0xFF1E293B) : Colors.white,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(color: isDark ? Colors.white10 : Colors.grey.shade300),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.05),
                        blurRadius: 5,
                        offset: const Offset(0, 2),
                      )
                    ],
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Header Row (Index & Remove)
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text("Item ${index + 1}", style: TextStyle(fontWeight: FontWeight.bold, color: isDark ? Colors.white54 : Colors.grey)),
                          if (_items.length > 1)
                            InkWell(
                              onTap: () => _removeItem(index),
                              child: const Padding(
                                padding: EdgeInsets.all(4.0),
                                child: Icon(Icons.close, size: 20, color: Colors.red),
                              ),
                            ),
                        ],
                      ),
                      const SizedBox(height: 12),

                      // Inputs
                      Row(
                        children: [
                          // Category Dropdown
                          Expanded(
                            flex: 2,
                            child: DropdownButtonFormField<String>(
                              value: item.category,
                              items: _categories.map((c) => DropdownMenuItem(value: c, child: Text(c, style: const TextStyle(fontSize: 13)))).toList(),
                              onChanged: (v) => setState(() => item.category = v!),
                              decoration: _inputDecoration("Category", isDark),
                              isExpanded: true,
                            ),
                          ),
                          const SizedBox(width: 10),

                          // Amount
                          Expanded(
                            flex: 2,
                            child: TextFormField(
                              controller: item.amountCtrl,
                              focusNode: item.amountFocus,
                              keyboardType: TextInputType.number,
                              style: const TextStyle(fontWeight: FontWeight.bold),
                              decoration: _inputDecoration("Amount", isDark),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 10),

                      // Note & Date
                      Row(
                        children: [
                          Expanded(
                            flex: 3,
                            child: TextFormField(
                              controller: item.noteCtrl,
                              decoration: _inputDecoration("Note (Optional)", isDark),
                            ),
                          ),
                          const SizedBox(width: 10),

                          // Date Picker
                          InkWell(
                            onTap: () async {
                              final picked = await showDatePicker(
                                context: context,
                                initialDate: item.date,
                                firstDate: DateTime(2020),
                                lastDate: DateTime(2030),
                              );
                              if (picked != null) {
                                setState(() => item.date = picked);
                              }
                            },
                            child: Container(
                              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 14),
                              decoration: BoxDecoration(
                                border: Border.all(color: isDark ? Colors.white24 : Colors.grey.shade400),
                                borderRadius: BorderRadius.circular(8),
                              ),
                              child: Row(
                                children: [
                                  const Icon(Icons.calendar_today, size: 16),
                                  const SizedBox(width: 8),
                                  Text(DateFormat('dd MMM').format(item.date)),
                                ],
                              ),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                );
              },
            ),
          ),

          // Bottom Bar
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: isDark ? const Color(0xFF0F172A) : Colors.white,
              boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.1), blurRadius: 10, offset: const Offset(0, -4))],
            ),
            child: Row(
              children: [
                Expanded(
                  child: OutlinedButton.icon(
                    onPressed: _addItem,
                    icon: const Icon(Icons.add),
                    label: const Text("Add Another"),
                    style: OutlinedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 16),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: ElevatedButton.icon(
                    onPressed: (_isLoading) ? null : _saveAll,
                    icon: const Icon(Icons.check),
                    label: _isLoading ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2)) : const Text("Save All"),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.redAccent,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(vertical: 16),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  InputDecoration _inputDecoration(String label, bool isDark) {
    return InputDecoration(
      labelText: label,
      labelStyle: TextStyle(color: isDark ? Colors.white60 : Colors.grey[600], fontSize: 13),
      contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: BorderSide(color: isDark ? Colors.white24 : Colors.grey.shade400),
      ),
    );
  }
}